### ISSUE TITLE
[QUESTION] 有些奇怪的IP在和我的服务器交互？

### ISSUE THREAD

**Issue by Thirace446** [auioc/arnicalib-mcmod#8]
### Description

图
https://imgur.com/a/KVyl1ZD

### Environment

处理器： i3-9100F
系统：Windows 10  专业版 21H2
整合包：FTB inferno
Forge版本：40.1.80
Mod版本：arnicalib-1.18.2-5.4.4

### Reproduction steps

下载FTB Inferno v1.0.0 服务端 启动

**Comment by WakelessSloth56** [comment]
当有服务端收到查询服务器状态请求（例如客户端进入服务器列表页面时、点击“刷新”按钮时、登录前）时会记录此信息，**ArnicaLib 仅负责记录**，出现“奇怪的IP”不可能是由 ArnicaLib 导致的。
若在某玩家登入前出现为正常现象，您可以通过查询玩家的地址是否与之相同来进一步验证。
若定期出现来自某地址的请求，或地址属于云服务，则可能是一些服务器列表网站（例如 https://play.mcmod.cn/ ）所致。

**Comment by Thirace446** [comment]
说实话，如果它没被检测显示出来在后台偷偷交互我反而还不会在意，
原先还以为是这个Mod需要在线获取什么资源前尝试ping到这些地址，
但是都是来自不同的云服务器的ip，且不可能是服务器列表，因为我也没把服务器宣传到任何站点，
那就可能是其他Mod干的反而被ArnicaLib检测到了。

**Comment by Thirace446** [comment]
https://imgur.com/a/Jf0FzS3
最上面最下面是我在刷新服务器列表 
确实如你所说 ArnicaLib会记录来自多人游戏菜单的刷新(ping)
是否有办法知道这些ip来自什么Mod发起的请求

**Comment by Thirace446** [comment]
我在Discord看到了相同的问题 
而且他们并不在意这些ip是否在ping他们的服务器 
只想隐藏这些垃圾反馈信息
但是似乎整合包的开发者并没有理

**Comment by WakelessSloth56** [comment]
此功能实际是在记录 `ServerListPing`（日志的 Marker 也有写明），通常来说与 Mod 没有任何关系，SLP 的细节可查看此处 https://wiki.vg/Server_List_Ping 。

目前 ArnicaLib 并不能禁用此记录，想要隐藏此记录可以使用 Log4j2 配置文件，或使用如 [DeLogger](https://www.curseforge.com/minecraft/mc-mods/delogger)、[Cuneiform](https://www.curseforge.com/minecraft/mc-mods/cuneiform) 等带有日志过滤功能的 Mod。

**Comment by WakelessSloth56** [comment]
若为来自云服务的地址，可以尝试通过 IP 地址反查域名来确定来源。
可能是您的玩家将您的服务器发布在了某些网站上或无意使用某些检测网站后被网站记录所致。

**Comment by Thirace446** [comment]
我可以确定这些ip和mod和服务端没有任何关系，
因为我开别的游戏后台也刷各种ip，
怀疑是之前在ip.sb上面ping了，所以被他记录了
总之还是谢谢你的解答
