### ISSUE TITLE
[SUGGESTION] 1.18.2 Console spam

### ISSUE THREAD

**Issue by Saereth** [auioc/arnicalib-mcmod#9]
### Description

With the mod installed consoles/logs are continually spammed with
 [Netty Epoll Server IO #2/INFO] [ArnicaLib/ServerListPing]: [/X.X.X.X:XXXXX] <-> InitialHandler has pinged

We've had several server operators contact us asking how to turn this off but I can't seem to find any config options for it

### Environment

linux ubuntuu 22

### Reproduction steps

install the mod, observer the console when players are connected

### Expected behavior

A config option to squelch this would be much appreciated

**Comment by WakelessSloth56** [comment]
Thanks for your feedback.

Currently there is no config option to disable this log.
In the next version we will add a config option to disable this log or just set the log level to DEBUG.

Temporarily, you can use [Log4j filter](https://logging.apache.org/log4j/2.x/manual/filters.html) or a mod with log filtering function (e.g. [Cuneiform](https://www.curseforge.com/minecraft/mc-mods/cuneiform)) to suppress this log.
